version: '3.5'
services:
  api1: # API - Instância 01
    image: docker.io/akitaonrails/rinhabackendapi
    environment:
      DB_HOST: db
      DB_POOL: 10
    hostname: api1
    depends_on:
      - db
      - memcached
    expose:
      - "3000"
    deploy:
      resources:
        limits:
          cpus: '0.25'
          memory: '0.5GB'

  api2: # API - Instância 01
    image: docker.io/akitaonrails/rinhabackendapi
    environment:
      DB_HOST: db
      DB_POOL: 10
    hostname: api2
    depends_on:
      - db
      - memcached
    expose:
      - "3000"
    deploy:
      resources:
        limits:
          cpus: '0.25'
          memory: '0.5GB'

  nginx: # Load Balancer
    image: docker.io/nginx:latest
    command: ["nginx", "-g", "daemon off;"]
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api1
      - api2
    ports:
      - "9999:9999"
    deploy:
      resources:
        limits:
          cpus: '0.20'
          memory: '0.5GB'

  db: # Banco de dados
   image: docker.io/postgres
   environment:
     POSTGRES_PASSWORD: password
   deploy:
      resources:
        limits:
          cpus: '0.70'
          memory: '1.3GB'

  memcached:
    image: memcached:latest
    ports:
      - "11211:11211"
    deploy:
      resources:
        limits:
          cpus: '0.10'
          memory: '0.2GB'
