version: '3.5'
services:
  api1: &api
    #image: docker.io/akitaonrails/rinhabackendapi:latest
    build: ./
    environment:
      DB_HOST: postgres
      DB_POOL: 45
      RAILS_MAX_THREADS: 4
      WEB_CONCURRENCY: 2
      RAILS_LOG_LEVEL: warn
      REDIS_HOST: redis
      REDIS_POOL_SIZE: 10
      JOB_BATCH_SIZE: 5
      JOB_FLUSH_TIMEOUT: 30
      CACHE_EXPIRES_SECONDS: 60
    hostname: api1
    depends_on:
      - postgres
      - redis
    expose:
      - "3000"
    ulimits:
      nproc: 1000000
      nofile:
        soft: 1000000
        hard: 1000000
    deploy:
      resources:
        limits:
          cpus: '0.45'
          memory: '0.4GB'

  api2:
    <<: *api
    hostname: api2

  nginx: # Load Balancer
    image: docker.io/nginx:latest
    command: ["nginx", "-g", "daemon off;"]
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api1
      - api2
    ports:
      - "9999:9999"
    ulimits:
      nproc: 1000000
      nofile:
        soft: 1000000
        hard: 1000000
    deploy:
      resources:
        limits:
          cpus: '0.15'
          memory: '0.5GB'

  postgres: # Banco de dados
    image: docker.io/postgres
    environment:
      POSTGRES_PASSWORD: password
    volumes:
      - ./db/schema.sql:/docker-entrypoint-initdb.d/schema.sql
      - ./postgresql.conf:/docker-entrypoint-initdb.d/postgresql.conf
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 5s
      timeout: 5s
      retries: 20
      start_period: 10s
    deploy:
      resources:
        limits:
          cpus: '0.9'
          memory: '1.4GB'

  redis:
    image: docker.io/redis:latest
    hostname: redis
    command: redis-server --save "" --appendonly no --maxclients 20000
    deploy:
      resources:
        limits:
          cpus: '0.15'
          memory: '0.3GB'
