version: '3.5'
services:
  api1: &api
    #image: docker.io/akitaonrails/rinhabackendapi:latest
    build: ./
    environment:
      DB_HOST: postgres
      DB_POOL: 200
      RAILS_MAX_THREADS: 100
      WEB_CONCURRENCY: 2
      RAILS_LOG_LEVEL: warn
      RAILS_ENV: production
      REDIS_HOST: redis
      REDIS_POOL_SIZE: 20
      JOB_BATCH_SIZE: 10
      CACHE_EXPIRES_SECONDS: 60
      RAILS_LOG_TO_STDOUT: 'true'
      RUBY_YJIT_ENABLE: 1
      RAILS_MASTER_KEY: 84ec93b5f81d27f8fdf7fc71d7b28e15
    hostname: api1
    depends_on:
      - postgres
      - redis
    expose:
      - "3000"
    networks:
      - mynetwork
    deploy:
      resources:
        limits:
          cpus: '0.45'
          memory: '0.4GB'

  api2:
    <<: *api
    hostname: api2

  sidekiq1: &sidekiq
    <<: *api
    hostname: sidekiq
    environment:
      DB_HOST: postgres
      DB_POOL: 1
      RAILS_MAX_THREADS: 1
      WEB_CONCURRENCY: 1
      RAILS_LOG_LEVEL: warn
      RAILS_ENV: production
      REDIS_HOST: redis
      REDIS_POOL_SIZE: 1
      JOB_BATCH_SIZE: 10
      JOB_FLUSH_TIMEOUT: 30
      CACHE_EXPIRES_SECONDS: 60
      RAILS_LOG_TO_STDOUT: 'true'
      RUBY_YJIT_ENABLE: 1
      RAILS_MASTER_KEY: 84ec93b5f81d27f8fdf7fc71d7b28e15
    command: /rails/bin/bundle exec sidekiq -c 1 -q insert_buffer
    deploy:
      resources:
        limits:
          cpus: '0.05'
          memory: '0.15GB'

  sidekiq2:
    <<: *sidekiq
    command: /rails/bin/bundle exec sidekiq -c 1 -q flush

  nginx: # Load Balancer
    image: docker.io/nginx:latest
    command: ["nginx", "-g", "daemon off;"]
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api1
      - api2
    ports:
      - "9999:9999"
    ulimits:
      nproc: 1000000
      nofile:
        soft: 1000000
        hard: 1000000
    networks:
      - mynetwork
    deploy:
      resources:
        limits:
          cpus: '0.1'
          memory: '0.3GB'

  postgres: # Banco de dados
    image: docker.io/postgres
    hostname: postgres
    environment:
      POSTGRES_USERNAME: postgres
      POSTGRES_PASSWORD: password
    command: postgres -c 'config_file=/etc/postgresql/postgresql.conf'
    expose:
      - "5432"
    volumes:
      - ./postgresql.conf:/etc/postgresql/postgresql.conf
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 5s
      timeout: 5s
      retries: 20
      start_period: 10s
    networks:
      - mynetwork
    deploy:
      resources:
        limits:
          cpus: '0.35'
          memory: '1.5GB'

  redis:
    image: docker.io/redis:latest
    hostname: redis
    command: redis-server --save "" --appendonly no --maxclients 20000
    expose:
      - "6379"
    networks:
      - mynetwork
    deploy:
      resources:
        limits:
          cpus: '0.05'
          memory: '0.1GB'

networks:
  mynetwork:
    driver: bridge
