version: '3.5'
services:
  api1: &api
    #image: docker.io/akitaonrails/rinhabackendapi:latest
    build: ./
    environment:
      DB_HOST: db
      DB_POOL: 25
      RAILS_MAX_THREADS: 5
      WEB_CONCURRENCY: 4
      RAILS_LOG_LEVEL: warn
      SUCKER_PUNCH_WORKERS: 2
      SUCKER_PUNCH_BATCH_SIZE: 10
      SUCKER_PUNCH_FLUSH_TIMEOUT: 30
      CACHE_EXPIRES_SECONDS: 90
    hostname: api1
    depends_on:
      - db
      - memcached
    expose:
      - "3000"
    ulimits:
      nproc: 1000000
      nofile:
        soft: 1000000
        hard: 1000000
    deploy:
      resources:
        limits:
          cpus: '1.5'
          memory: '1.5GB'

  api2:
    <<: *api
    hostname: api2

  api3:
    <<: *api
    hostname: api3

  api4:
    <<: *api
    hostname: api4

  api5:
    <<: *api
    hostname: api5

  api6:
    <<: *api
    hostname: api6

  api7:
    <<: *api
    hostname: api7

  api8:
    <<: *api
    hostname: api8

  nginx: # Load Balancer
    image: docker.io/nginx:latest
    command: ["nginx", "-g", "daemon off;"]
    volumes:
      - ./nginx-ideal.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api1
      - api2
      - api3
      - api4
    ports:
      - "9999:9999"
    ulimits:
      nproc: 1000000
      nofile:
        soft: 1000000
        hard: 1000000
    deploy:
      resources:
        limits:
          cpus: '1.5'
          memory: '1.5GB'

  db: # Banco de dados
    image: docker.io/postgres
    environment:
      POSTGRES_PASSWORD: password
    volumes:
      - ./postgresql-ideal.conf:/etc/postgresql/postgresql.conf
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 5s
      timeout: 5s
      retries: 20
      start_period: 10s
    ulimits:
      nproc: 1000000
      nofile:
        soft: 1000000
        hard: 1000000
    deploy:
      resources:
        limits:
          cpus: '8'
          memory: '4GB'

  memcached:
    image: memcached:latest
    ports:
      - "11211:11211"
    deploy:
      resources:
        limits:
          cpus: '4'
          memory: '4GB'
